Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel $\rightarrow$ Restart) and then **run all cells** (in the menubar, select Cell $\rightarrow$ Run All).

Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE", as well as your name and collaborators below:

In [2]:
NAME = " 양동훈 "
COLLABORATORS = "12210472"

---

# Exercise: Gauss Eliniation, LU Decomposition
**강좌**: *Numerical Analysis*

**Due**: 2024/10/21

## Problem #1
Write a function to solve $Ax=b$ using Gauss Elimination with Partial Pivoting. The function should follow these specifications:

- Input parameters
   * Matrix *A*
   * vector *b*
   
- Return parameters
   * solution vector *x*
   * Pivot indices *l* (indicating row swaps during pivoting)
   
- Additionally, include a proper docstring to describe the function's behavior, parameters, and return values.

In [3]:
import numpy as np


def pv_gauss_eliminate(A, b):
    # YOUR CODE HERE
    """
    Gauss Elimination

    Parameters
    ----------
    a : matrix
        Linear operator
    b : array
        Result

    Returns
    --------
    x : array
        Solution
    """

    # Check size
    m, n = np.array(A).shape
    lenth = len(b)
    l = list(range(lenth))

    if (m != n) or (n != lenth) or (m != lenth):
        raise ValueError('Wrong shape', m,n,b)

    # Forward elimiation
    for i in range(n-1) :
      j = np.argmax(abs(A[l[i:], i])) + i
      l[j], l[i] = l[i], l[j]
      j= l[i]
      for k in l[i+1:] :
        ratio = A[k, i]/A[j, i]
        A[k, i:] = A[k, i:] - ratio*A[j, i:]
        b[k] = b[k] - ratio*b[j]
    # Recorder A, b
    A = A[l, :]
    b = b[l]

    x = np.empty(n)

    for i in range(n-1, -1, -1):
        x[i] = b[i]

        for j in range(i+1, n):
            x[i] -= A[i, j]*x[j]

        x[i] /= A[i,i]

    return x, l

In [4]:
## Do not remove
A = np.array([
    [3, -13, 9, 3],
    [-6, 4, 1, -18],
    [6, -2, 2, 4],
    [12, -8, 6, 10]
])

b = np.array([-19, -34, 16, 26])
x, l = pv_gauss_eliminate(A, b)

# Check your result
assert np.linalg.norm(x - np.array([3, 1, -2, 1])) < 1e-6
assert np.linalg.norm(l - np.array([3, 0, 1, 2])) < 1e-6

## Problem #2
Write two functions to perform LU decomposition ($A=LU$) and substitutions to solve $Ax=b$ using forward and backward substitutions with the following specifications:

- LU decomposition function
    * Convert matrix A into its LU decomposed form.
    
- LU substitution function
    * Input parameters
       * Matrix *LU* (from the LU decomposition)
       * vector *b* (right-hand side of the equation)
       
    - Return parameters
       * solution vector *x* (final solution to $Ax=b$)
       * Intermediate result of forward substitution $Lc=b$
       
- Additionally, include a proper docstring to describe the function's behavior, parameters, and return values.

In [9]:
def lu_decompose(A):
    '''
    Lu decompose function

    Parameters
    ----------
    n : int
        size of matrix
    i : int
        row of pivot
    j : int
        row of elimination
    ratio : float
        elimination cofficeint
    '''
    
    n = A.shape[0]
    for i in range(n) :
        for j in range(i+1,n) :
            ratio = A[j, i] / A[i, i]
            A[j,i] = ratio
            A[j, i+1:] = A[j, i+1:] - ratio*A[i, i+1:]

    return A #LU가 결합된 matrix를 반환한다. strictly lower triangular부분에는 ratio 값들이 입력되어 있고, upper trianglular부분에는 가우스 소거법 된 값들이 있다.

def lu_subs(A, b):
    '''
    Forward substution and Backward substution

    Parameters
    ----------
    A : array
        Lu decompose 된 matrix     
    b : array
        결과값
    x : array
        solution
    c : array
        gauss elimination으로 인한 변화된 결과값
    '''
    n = b.shape[0]
    x = np.zeros_like(b) #b의 모양으로 비워둔다 아마 아무값이나 들어가는 거일듯 zeros 써도 됨

    #forward 
    for i in range(n) :
        for j in range(i) :
            b[i] -= A[i,j]*b[j]
    c = b
    #backward 
    for i in range(n-1, -1, -1):
        x[i] = b[i]

        for j in range(i+1, n):
            x[i] -= A[i, j]*x[j]

        x[i] /= A[i,i]
    return x, c


In [12]:
## Do not remove
A = np.array([[2, 1, 1], [4, -6, 0], [-2, 7, 2]])
LU = A.copy()

# LU decomposition
lu_decompose(LU)
# Solve Ax=b
b = np.array([5, -2, 9])
x, c = lu_subs(LU, b)

# Check your result
assert np.linalg.norm(LU - np.array([[2, 1, 1], [2, -8, -2], [-1, -1, 1]])) < 1e-6
assert np.linalg.norm(x - np.array([1, 1, 2])) < 1e-6
assert np.linalg.norm(c - np.array([5, -12, 2])) < 1e-6

## Problem #3
Write a function to compute the inverse of matrix AA using LU decomposition and substitution.

In [10]:
def lu_decompose(A):
    '''
    Lu decompose function

    Parameters
    ----------
    n : int
        size of matrix
    i : int
        row of pivot
    j : int
        row of elimination
    ratio : float
        elimination cofficeint
    '''
    
    n = A.shape[0]
    for i in range(n) :
        for j in range(i+1,n) :
            ratio = A[j, i] / A[i, i]
            A[j,i] = ratio
            A[j, i+1:] = A[j, i+1:] - ratio*A[i, i+1:]

    return A #LU가 결합된 matrix를 반환한다. strictly lower triangular부분에는 ratio 값들이 입력되어 있고, upper trianglular부분에는 가우스 소거법 된 값들이 있다.

def lu_subs(A, b):
    '''
    Forward substution and Backward substution

    Parameters
    ----------
    A : array
        Lu decompose 된 matrix     
    b : array
        결과값
    x : array
        solution
    c : array
        gauss elimination으로 인한 변화된 결과값
    '''
    n = b.shape[0]
    x = np.empty_like(b)

    #forward 
    for i in range(n) :
        for j in range(i) :
            b[i] -= A[i,j]*b[j]
    c = b
    #backward 
    for i in range(n-1, -1, -1):
        x[i] = b[i]

        for j in range(i+1, n):
            x[i] -= A[i, j]*x[j]

        x[i] /= A[i,i]
    return x, c

def inverse(A):
    '''
    Finding inverse of A 

    Parameters
    ----------
    A : array
        역행렬을 구하고자 하는 값
    A_inv : array
        solution
    n : int
        size of matrix
    I : array
        identity matrix
    '''
    n = A.shape[0]
    I = np.eye(n)
    A_LU = lu_decompose(A.copy())
    A_inv = np.zeros_like(A,dtype=float) #dtype을 float으로 안해주면 정수에서 짤라서 계산해서 오차가 커진다.
    
    #forward substitution
    for col in range(n) :
        b = I[:, col]
        x , c = lu_subs(A_LU, b)
        for i in range(n) :
            A_inv[i,col] = x[i]
    return A_inv

In [11]:
## Do not remove
A = np.array([[2,1,1],[4,-6,0],[-2,7,2]])
A_inv = inverse(A)

# Check your result
assert np.linalg.norm(A @ A_inv - np.eye(len(A))) < 1e-6

## Problem #4
Write a function to solve a tri-diagonal system using the Thomas algorithm to solve the following problem:

$$
\begin{bmatrix}
2.01475 & -0.020875 & & \\
-0.020875 & 2.01475 & -0.020875 & \\
& -0.020875 & 2.01475 & -0.020875 \\
& & -0.020875 & 2.01475
\end{bmatrix}
T
=
\begin{bmatrix}
4.175 \\ 0 \\ 0 \\ 2.0875
\end{bmatrix}
$$

In [8]:
def thomas(a, b, c, d):
    n = len(a)
    x = np.empty_like(a)

    # Forward sweep
    for i in range(1, n):
        w = a[i] / b[i-1]
        b[i] -= w*c[i-1]
        d[i] -= w*d[i-1]

    # Backward sweep    
    x[-1] = d[-1] / b[-1]
    for i in range(n-2, -1, -1):
        x[i] = (d[i] - c[i]*x[i+1]) / b[i]

    return x
a = np.array([0, -0.020875, -0.020875, -0.020875])
b = np.array([2.01475, 2.01475, 2.01475, 2.01475])
c = np.array(a[::-1])
d = np.array([4.175, 0, 0, 2.0875])
print(thomas(a,b,c,d))

[2.07244105 0.0215863  0.01096005 1.03622226]


In [9]:
# Solve the given linear system, store the solution in the vector x.
# YOUR CODE HERE
a = np.array([0, -0.020875, -0.020875, -0.020875])
b = np.array([2.01475, 2.01475, 2.01475, 2.01475])
c = np.array(a[::-1])
d = np.array([4.175, 0, 0, 2.0875])
              
x = thomas(a,b,c,d)
print(x)

[2.07244105 0.0215863  0.01096005 1.03622226]


In [130]:
# Do not remove!!!

In [8]:
import numpy as np 
A = np.array([[3, 2, -4], [2, 3, 3], [5, -3, 1]], dtype= float)
b = np.array([3, 15, 14], dtype= float)

def pv_gauss_eliminate(A, b):
    # YOUR CODE HERE
    """
    Gauss Elimination

    Parameters
    ----------
    a : matrix
        Linear operator
    b : array
        Result

    Returns
    --------
    x : array
        Solution
    """

    # Check size
    m, n = np.array(A).shape
    lenth = len(b)
    l = list(range(lenth))

    if (m != n) or (n != lenth) or (m != lenth):
        raise ValueError('Wrong shape', m,n,b)

    # Forward elimiation
    for i in range(n-1) :
      j = np.argmax(abs(A[l[i:], i])) + i
      l[j], l[i] = l[i], l[j]
      j= l[i]
      for k in l[i+1:] :
        ratio = A[k, i]/A[j, i]
        A[k, i:] = A[k, i:] - ratio*A[j, i:]
        b[k] = b[k] - ratio*b[j]
    # Recorder A, b
    A = A[l, :]
    b = b[l]

    x = np.empty(n)

    for i in range(n-1, -1, -1):
        x[i] = b[i]

        for j in range(i+1, n):
            x[i] -= A[i, j]*x[j]

        x[i] /= A[i,i]

    return x, l

In [9]:
pv_gauss_eliminate(A,b)

(array([3., 1., 2.]), [2, 1, 0])